name: Build Docker Image SNFIN

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pegar o código
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # necessário para pegar tags do Git

      # 2️⃣ Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build da imagem Docker com tag do Git
      - name: Build Docker image
        run: |
          IMAGE_NAME="samukaoliveira/snfin"
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "latest")
          echo "Buildando $IMAGE_NAME:$TAG"
          docker build -t $IMAGE_NAME:$TAG .

      # 5️⃣ Push para o Docker Hub
      - name: Push Docker image
        run: |
          IMAGE_NAME="samukaoliveira/snfin"
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "latest")
          echo "Pushando $IMAGE_NAME:$TAG"
          docker push $IMAGE_NAME:$TAG
